### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by DarkstaIkers** [nadeko/hexchat-mpc-nowplaying#1]
I'm facing this error:

>  File "<string>", line 9, in <module>
>  ImportError: No module named 'requests'
>  Error loading module C:\Software\HexChat\config\addons\hexchat.mpc.nowplaying.py

I'm using python 3.5.2

**Comment by nadeko** [comment]
Hello. One of the requirements to use this is requests for Python. This is partially my fault for not explaining how to get them but what you'll have to do is open an administrator command prompt and type ``python pip install requests`` and do the same for the other requirements. I'll need to update the Readme to have better instructions. I didn't think anyone would use this honestly as this was a hobby project of mine.  :)

**Comment by DarkstaIkers** [comment]
Hehe, there will be always people lurking for new alternatives! 

I did install requests and now it works flawless. Thanks a bunch, mate.

**Comment by nadeko** [comment]
Glad you got it working!
